name: Archive

on:
  workflow_dispatch:
  schedule:
    - cron: "00 00 * * *"

jobs:
  archive:
    runs-on: ubuntu-latest
    env:
      DENO_VERSION: "v1.x"
      MNEMOSYNE_ARCHIVES_DIR: archives
      MNEMOSYNE_MODRINTH_API_HOST: api.modrinth.com
      MNEMOSYNE_MODRINTH_API_ENDPOINT: https://api.modrinth.com/v2
      MNEMOSYNE_MODRINTH_USER: ${{ github.repository_owner }}
      MNEMOSYNE_USER_AGENT: ${{ github.repository }}@${{ github.sha }}

    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: archives
          path: ${{ env.MNEMOSYNE_ARCHIVES_DIR }}

      - name: Set up Deno ${{ env.DENO_VERSION }}
        uses: denoland/setup-deno@v1
        with:
          deno-version: ${{ env.DENO_VERSION }}

      - name: Execute
        run: |
          deno run \
            --allow-env \
            --allow-read=./ \
            --allow-write=./${{ env.MNEMOSYNE_ARCHIVES_DIR }} \
            --allow-net=${{ env.MNEMOSYNE_MODRINTH_API_HOST }} \
            src/app.ts
          deno fmt

      - name: Commit and Push
        run: |
          cd archives
          git config --local user.email "38515249+Aton-Kish@users.noreply.github.com"
          git config --local user.name "Aton-Kish"
          git add .
          git commit -m "Update from ${{ github.repository }}@${{ github.sha }}"
          git push

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: failure()
        env:
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: danger
          SLACK_TITLE: Archive job fails
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
